module.exports = {
  extends: 'airbnb',
  "env": {
    "browser": true,
    "node": true,
  },
  rules: {
    'array-bracket-spacing': 'off',
    'arrow-body-style': ['warn', 'as-needed', { requireReturnForObjectLiteral: false }],
    'arrow-parens': 'off',
    'arrow-spacing': 'off',
    'block-spacing': 'off',
    'brace-style': 'off',
    'camelcase': ['warn', { properties: 'never' }],
    'class-methods-use-this': ['warn', {
      exceptMethods: [
        'render',
        'getInitialState',
        'getDefaultProps',
        'getChildContext',
        'componentWillMount',
        'componentDidMount',
        'componentWillReceiveProps',
        'shouldComponentUpdate',
        'componentWillUpdate',
        'componentDidUpdate',
        'componentWillUnmount',
      ],
    }],
    'comma-dangle': 'off',
    'comma-spacing': 'off',
    'comma-style': 'off',
    'computed-property-spacing': 'off',
    'curly': 'off',
    'dot-location': 'off',
    'eol-last': 'off',
    'func-call-spacing': 'off',
    'generator-star-spacing': 'off',
    'indent': 'off',
    'jsx-quotes': 'off',
    'key-spacing': 'off',
    'keyword-spacing': 'off',
    'lines-around-directive': 'off',
    'max-len': 'off',
    'new-parens': 'warn',
    'newline-per-chained-call': 'off',
    'no-bitwise': 'warn',
    'no-continue': 'warn',
    'no-debugger': 'warn',
    'no-else-return': 'off',
    'no-empty': 'off',
    'no-empty-character-class': 'warn',
    'no-empty-function': 'off',
    'no-eq-null': 'off',
    'no-extra-bind': 'warn',
    'no-extra-boolean-cast': 'warn',
    'no-extra-semi': 'off',
    'no-lonely-if': 'warn',
    'no-mixed-spaces-and-tabs': 'off',
    'no-multi-spaces': 'off',
    'no-multiple-empty-lines': 'off',
    'no-plusplus': 'warn',
    'no-shadow': 'warn',
    'no-spaced-func': 'off',
    'no-tabs': 'off',
    'no-trailing-spaces': 'off',
    'no-undef-init': 'warn',
    'no-unexpected-multiline': 'warn',
    'no-unneeded-ternary': ['warn', { defaultAssignment: false }],
    'no-unreachable': 'warn',
    'no-unused-labels': 'warn',
    'no-unused-vars': ['warn', { vars: 'local', args: 'after-used' }],
    'no-useless-call': 'warn',
    'no-useless-concat': 'warn',
    'no-useless-escape': 'warn',
    'no-useless-return': 'warn',
    'no-whitespace-before-property': 'off',
    'object-curly-spacing': 'off',
    'object-property-newline': 'off',
    'one-var-declaration-per-line': 'off',
    'operator-assignment': ['warn', 'always'],
    'padded-blocks': 'off',
    'prefer-template': 'warn',
    'quotes': 'off',
    'rest-spread-spacing': 'off',
    'semi': 'off',
    'semi-spacing': 'off',
    'space-before-blocks': 'off',
    'space-before-function-paren': 'off',
    'space-in-parens': 'off',
    'space-infix-ops': 'off',
    'space-unary-ops': 'off',
    'spaced-comment': 'off',
    'template-curly-spacing': 'off',
    'vars-on-top': 'off',
    'yield-star-spacing': 'off',
    'yoda': 'warn',

    'import/first': ['warn', 'absolute-first'],
    'import/newline-after-import': 'off',
    'import/prefer-default-export': 'warn',

    'jsx-a11y/href-no-hash': ['warn', { components: ['a'] }],
    'jsx-a11y/img-has-alt': 'warn',
    'jsx-a11y/img-redundant-alt': 'warn',
    'jsx-a11y/label-has-for': ['warn', { components: ['label'] }],

    'react/forbid-prop-types': 'off',
    'react/jsx-boolean-value': ['warn', 'never'],
    'react/jsx-closing-bracket-location': 'off',
    'react/jsx-curly-spacing': 'off',
    'react/jsx-equals-spacing': 'off',
    'react/jsx-filename-extension': 'off',
    'react/jsx-first-prop-new-line': 'off',
    'react/jsx-indent': 'off',
    'react/jsx-indent-props': 'off',
    'react/jsx-no-bind': ['warn', {
      ignoreRefs: true,
      allowArrowFunctions: true,
      allowBind: false,
    }],
    'react/jsx-no-duplicate-props': ['warn', { ignoreCase: true }],
    'react/jsx-no-target-blank': 'warn',
    'react/jsx-pascal-case': ['warn', {
      allowAllCaps: true,
      ignore: [],
    }],
    'react/jsx-space-before-closing': 'off',
    'react/jsx-tag-spacing': 'off',
    'react/jsx-wrap-multilines': 'off',
    'react/no-deprecated': 'warn',
    'react/no-direct-mutation-state': 'error',
    'react/no-find-dom-node': 'warn',
    'react/no-multi-comp': 'off',
    'react/no-unescaped-entities': 'off',
    'react/no-unused-prop-types': ['warn', { skipShapeProps: true }],
    'react/prefer-stateless-function': 'warn',
    'react/prop-types': 'warn',
    'react/require-default-props': 'warn',
    'react/self-closing-comp': 'warn',
    'react/sort-comp': ['warn', {
      order: [
        'static-methods',
        'lifecycle',
        '/^on.+$/',
        '/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/',
        'everything-else',
        '/^render.+$/',
        'render'
      ],
    }],
  },
};
